name: Chown workspace

description: Ensure that the working directory gets chowned back to the current user

runs:
  using: composite
  steps:
    - run: docker run --rm -v "$(pwd)":/v -w /v "${ALPINE_IMAGE}" chown -R "$(id -u):$(id -g)" .
      shell: bash
      env:
        ALPINE_IMAGE: "alpine"
